In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
import numpy as np

POST LAB

In [3]:


a = load_iris(as_frame=True)
a = pd.DataFrame(data=a.data)



In [4]:
a.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [5]:
k = a-a.mean()

In [6]:
cov_mat = np.cov(k.T)

In [7]:
eig_val,eig_vec = np.linalg.eig(cov_mat)

In [8]:
print(eig_vec)

[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]


IN LAB  
WITHOUT PCA

In [9]:
mat = np.array([[3,5],[4,2],[1,6]])
mat = pd.DataFrame(data=mat)
mat

0  1
0  3  5
1  4  2
2  1  6

In [10]:
cov = np.cov(mat.T)
cov


array([[ 2.33333333, -2.83333333],
       [-2.83333333,  4.33333333]])

In [11]:
eig_value,eig_vecter = np.linalg.eig(cov)
print(eig_vecter)

[[-0.81633943  0.57757246]
 [-0.57757246 -0.81633943]]


WITH PCA FUNCTION

In [12]:
pca = PCA(n_components=2)
mat1 = pca.fit_transform(mat)

In [13]:
a =pca.components_
print(a)

[[-0.57757246  0.81633943]
 [ 0.81633943  0.57757246]]
